import test, { describe, before, after } from 'node:test';
import assert from 'node:assert/strict';
import pg from 'pg';
import { PostgresAdmin } from './admin.js';
import { PostgresIsolationAdapter } from './adapter.js';
import { makeTenantIdentifier, tenantRoleName } from '../identifiers.js';
import type { DataIsolationMode, IsolationContext, IsolationManifest, TargetResources } from '../types.js';

const TEST_URL = process.env.TEST_DATABASE_URL;

/**
 * structure: 'clone-shared' — o produto não fornece migrações; o adapter cria
 * as tabelas do tenant a partir da tabela compartilhada e mantém as
 * sequências do destino à frente dos dados copiados.
 */
describe('clone-shared table structure (integration)', { skip: !TEST_URL ? 'TEST_DATABASE_URL not set' : undefined }, () => {
  const tenant = 'clone-tenant-c';
  const other = 'clone-tenant-d';
  const schema = makeTenantIdentifier('schema', tenant);
  const db = makeTenantIdentifier('db', tenant);

  let admin: PostgresAdmin;
  let adapter: PostgresIsolationAdapter;
  let schemaTarget: TargetResources;
  let databaseTarget: TargetResources;
  const urls: Record<string, string> = {};

  const manifest: IsolationManifest = {
    apiVersion: 'organator.io/v1alpha1',
    product: 'clone-test',
    structure: 'clone-shared',
    tenantScopedTables: [{ schema: 'public', table: 'invoices', tenantColumn: 'tenant_id', primaryKey: 'id' }],
    async applyMigrations() {},
    async validate() {
      return { rowCounts: {}, checksums: {}, validatedAt: new Date().toISOString() };
    },
  };

  const sharedSource: TargetResources = { mode: 'SHARED', database: '', schema: 'public', role: '', resourceIds: {} };

  const context = (sourceMode: DataIsolationMode, source: TargetResources, targetMode: DataIsolationMode): IsolationContext => ({
    tenantId: tenant,
    generation: 1,
    sourceMode,
    targetMode,
    source,
    sourceConnection: { id: `${sourceMode}:${tenant}`, mode: sourceMode },
    manifest,
    resolveConnection: async () => '',
    storeConnection: async (input) => {
      urls[input.mode] = input.url;
      return { reference: { id: `${input.mode}:${input.tenantId}`, mode: input.mode }, encryptedPayload: { url: input.url } };
    },
  });

  async function runAs<T extends pg.QueryResultRow>(url: string, sql: string, values: unknown[] = []): Promise<T[]> {
    const client = new pg.Client({ connectionString: url });
    await client.connect();
    try {
      return (await client.query<T>(sql, values)).rows;
    } finally {
      await client.end();
    }
  }

  async function reset() {
    await admin.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
    await admin.query(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = $1 AND pid <> pg_backend_pid()`, [db]);
    await admin.query(`DROP DATABASE IF EXISTS "${db}"`);
    await admin.query('DROP TABLE IF EXISTS public.invoices');
    for (const role of [tenantRoleName(tenant, 'SCHEMA'), tenantRoleName(tenant, 'DATABASE')]) {
      if (await admin.roleExists(role)) {
        await admin.query(`DROP OWNED BY "${role}" CASCADE`);
        await admin.query(`DROP ROLE "${role}"`);
      }
    }
  }

  before(async () => {
    admin = new PostgresAdmin(TEST_URL!);
    adapter = new PostgresIsolationAdapter({ adminUrl: TEST_URL!, storeConnection: context('SHARED', sharedSource, 'SCHEMA').storeConnection });
    await reset();
    await admin.query(`
      CREATE TABLE public.invoices (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id text NOT NULL,
        amount numeric(10,2) NOT NULL DEFAULT 0,
        created_at timestamptz NOT NULL DEFAULT now(),
        note text
      )`);
    await admin.query(
      `INSERT INTO public.invoices (tenant_id, amount, note) VALUES ($1, 10.50, 'c1'), ($2, 99, 'd1'), ($1, 20, 'c2'), ($1, 30.25, NULL)`,
      [tenant, other],
    );
  });

  after(async () => {
    await adapter.close();
    await reset();
    await admin.close();
  });

  test('SHARED -> SCHEMA creates the table from the shared layout and keeps identities usable', async () => {
    const ctx = context('SHARED', sharedSource, 'SCHEMA');
    schemaTarget = await adapter.prepareTarget(ctx);
    await adapter.applyMigrations(ctx, schemaTarget);
    const copy = await adapter.copyData(ctx, schemaTarget);
    assert.deepEqual(copy.rowCounts, { invoices: 3 });
    await adapter.validate(ctx, schemaTarget);

    // O tenant insere sem informar id: a identity do destino não colide com os ids copiados.
    const inserted = await runAs<{ id: string }>(
      urls.SCHEMA,
      `INSERT INTO invoices (tenant_id, amount) VALUES ($1, 5) RETURNING id`,
      [tenant],
    );
    assert.equal(Number(inserted[0].id), 5);
  });

  test('SCHEMA -> DATABASE recreates columns, defaults, NOT NULL and PK in the tenant database', async () => {
    const ctx = context('SCHEMA', schemaTarget, 'DATABASE');
    databaseTarget = await adapter.prepareTarget(ctx);
    await adapter.applyMigrations(ctx, databaseTarget);
    const copy = await adapter.copyData(ctx, databaseTarget);
    assert.deepEqual(copy.rowCounts, { invoices: 4 });
    await adapter.validate(ctx, databaseTarget);

    const columns = await runAs<{ column_name: string; data_type: string; is_nullable: string; column_default: string | null; is_identity: string }>(
      urls.DATABASE,
      `SELECT column_name, format_type(a.atttypid, a.atttypmod) AS data_type, c.is_nullable, c.column_default, c.is_identity
         FROM information_schema.columns c
         JOIN pg_attribute a ON a.attrelid = 'public.invoices'::regclass AND a.attname = c.column_name
        WHERE c.table_schema = 'public' AND c.table_name = 'invoices'
        ORDER BY c.ordinal_position`,
    );
    const byName = Object.fromEntries(columns.map((c) => [c.column_name, c]));
    assert.equal(byName.id.is_identity, 'YES');
    assert.equal(byName.amount.data_type, 'numeric(10,2)');
    assert.equal(byName.amount.is_nullable, 'NO');
    assert.match(byName.created_at.column_default ?? '', /now\(\)/);
    assert.equal(byName.note.is_nullable, 'YES');

    const inserted = await runAs<{ id: string; amount: string }>(
      urls.DATABASE,
      `INSERT INTO public.invoices (tenant_id) VALUES ($1) RETURNING id, amount`,
      [tenant],
    );
    assert.equal(Number(inserted[0].id), 6);
    assert.equal(inserted[0].amount, '0.00');
  });

  test('applyMigrations is idempotent', async () => {
    await adapter.applyMigrations(context('SCHEMA', schemaTarget, 'DATABASE'), databaseTarget);
    const rows = await runAs<{ count: string }>(urls.DATABASE, 'SELECT COUNT(*) AS count FROM public.invoices');
    assert.equal(rows[0].count, '5');
  });

  test('fails clearly when the template table does not exist', async () => {
    const broken: IsolationManifest = { ...manifest, tenantScopedTables: [{ schema: 'public', table: 'missing', tenantColumn: 'tenant_id', primaryKey: 'id' }] };
    await assert.rejects(
      adapter.applyMigrations({ ...context('SCHEMA', schemaTarget, 'DATABASE'), manifest: broken }, databaseTarget),
      /missing/,
    );
  });
});
